apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::340752838251:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-obldpCsd3SiK
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers:
    - groups:
      - default-trainee
      userarn: arn:aws:iam::340752838251:user/sudhakar
      username: sudhakar
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-24T05:17:47Z"
  name: aws-auth
  namespace: kube-system
  uid: e2f0b56d-5942-4236-add6-6a8824869fcb